<?php 
$not='<RequestSkybill xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><Customeraccount>TIMES-TEST</Customeraccount><Username>timestest</Username><Password>timestest2018</Password><Skybillprefix/><Skybillnumber/><CustomerFreightCharges>0</CustomerFreightCharges><Shippername>邱泓旭</Shippername><Shippercompanyname>Club Factory</Shippercompanyname><Shipperaddress>No.239 Jingyu Road, Yuhang District,Hangzhou</Shipperaddress><Shippercountryisocode>CN</Shippercountryisocode><Shippercountry>CHINA</Shippercountry><Shippercityid>0</Shippercityid><Shippercity>Hangzhou</Shippercity><Shipperstateid>0</Shipperstateid><Shipperstate>Zhejiang</Shipperstate><Shipperzipcode>310004</Shipperzipcode><Shipperemail/><Shippertelephone>13429602265</Shippertelephone><Shipperfax/><Shipperidentificationnumber/><Consigneename>Francisco García hur</Consigneename><Consigneecompanyname>Club Factory</Consigneecompanyname><Consigneeaddress>Lorenzo Duarte #5 manzana d-38,col Benjamin Méndez aguilar,entre 20 de noviembre y cuahutemoc</Consigneeaddress><Consigneecountryisocode>MX</Consigneecountryisocode><Consigneecountry>Mexico</Consigneecountry><Consigneestateid>0</Consigneestateid><Consigneestate>Michoacan</Consigneestate><Consigneecityid>0</Consigneecityid><Consigneecity>Acámbaro</Consigneecity><Consigneezipcode>38630</Consigneezipcode><Consigneetelephone>4434101502</Consigneetelephone><Consigneefax/><Consigneeidentificationnumber/><Specialprice>0</Specialprice><Specialpricenumber/><Dangerousgoods/><Dangerousgoodsnumber/><Cod>0</Cod><Codnumber/><Freedomicilie>1</Freedomicilie><Insurance>0</Insurance><Signaturerequired>false</Signaturerequired><Comodity>42</Comodity><Typeofservice>EC</Typeofservice><Typeofshipment>SPX</Typeofshipment><Contractorreference/><Description>Cartoon Small Rabbit Wallet, </Description><Currency>MXN</Currency><Comercialvalue>2.48</Comercialvalue><Customvalue>2.48</Customvalue><Customeraccountingcode/><Shipperreference/><SkybillPieces><SkybillPiece><Itemnumber>1</Itemnumber><Weight>0.500</Weight><Volweight>0.500</Volweight><Length>1.000</Length><Width>1.000</Width><Height>1.000</Height><Products><Product><Articleid>0</Articleid><Quantity>1</Quantity><Productvalue>2.48</Productvalue><Productvaluecurrency>MXN</Productvaluecurrency><Productchargeableweight>0.500</Productchargeableweight><Commodityid>42</Commodityid><Countryofmanufacture>China</Countryofmanufacture></Product></Products></SkybillPiece></SkybillPieces></RequestSkybill> ';

$xml=new SimpleXMLElement('<?xml version="1.0" encoding="UTF-8"?>'.$not,null,false);
$xml = json_decode(json_encode($xml),true);
$result=[];
$result['consigneePhone']= $xml['Consigneetelephone'];
$result['consigneeDistrict']= $xml['Consigneecity'];
$result['consigneeProvince']= $xml['Consigneestate'];
$result['consigneeContactNameLocale']= $xml['Consigneename'];
$result['consigneeAddressLocale']= $xml['Consigneeaddress'];
$result['consigneePostalCode']= $xml['Consigneezipcode'];

var_dump($result);echo '<hr/>';

